/**
    Copyright 2017 Andrea "Stock" Stocchero

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package org.pepstock.charba.client.annotation;

import org.pepstock.charba.client.resources.AbstractInjectableResource;
import org.pepstock.charba.client.resources.ResourceName;

/**
 * Contains the content of <code>chartjs-plugin-annotation.min.js</code> to inject.<br>
 * 
 * @author Andrea "Stock" Stocchero
 *
 */
public final class AnnotationPluginResource extends AbstractInjectableResource {

	// encoded javascript content of chartjs-plugin-annotation.min.js
	private static final String[] CONTENT = {
		"/*!",
		"* chartjs-plugin-annotation v1.0.0-beta.3",
		"* undefined",
		" * (c) 2021 chartjs-plugin-annotation Contributors",
		" * Released under the MIT License",
		" */",
		"!function(t,e){\"object\"==typeof exports&&\"undefined\"!=typeof module?module.exports=e(require(\"chart.js\"),require(\"chart.js/helpers\")):\"function\"==typeof define&&define.amd?define([\"chart.js\",\"chart.js/helpers\"],e):(t=\"undefined\"!=typeof globalThis?globalThis:t||self)[\"chartjs-plugin-annotation\"]=e(t.Chart,t.Chart.helpers)}(this,(function(t,e){\"use strict\";const n=[\"click\",\"dblclick\"],i=[\"enter\",\"leave\"],o=n.concat(i);function a(t,e,n,i){if(e.listened)switch(n.type){case\"mousemove\":case\"mouseout\":!function(t,e,n){if(!e.moveListened)return;let i;\"mousemove\"===n.type&&(i=r(e.elements,n));const o=e.hovered;e.hovered=i,function(t,e,n,i){n&&n!==i&&s(t,e,n.options.leave||e.listeners.leave,n);i&&i!==n&&s(t,e,i.options.enter||e.listeners.enter,i)}(t,e,o,i)}(t,e,n);break;case\"click\":!function(t,e,n,i){const o=e.listeners,a=r(e.elements,n);if(a){const n=a.options,r=n.dblclick||o.dblclick,l=n.click||o.click;a.clickTimeout?(clearTimeout(a.clickTimeout),delete a.cl",
		"ickTimeout,s(t,e,r,a)):r?a.clickTimeout=setTimeout((()=>{delete a.clickTimeout,s(t,e,l,a)}),i.dblClickSpeed):s(t,e,l,a)}}(t,e,n,i)}}function s(t,n,i,o){e.callback(i,[{chart:t,element:o}])}function r(t,n){let i=Number.POSITIVE_INFINITY;return t.filter((t=>t._display&&t.inRange(n.x,n.y))).reduce(((t,o)=>{const a=o.getCenterPoint(),s=e.distanceBetweenPoints(n,a);return s<i?(t=[o],i=s):s===i&&t.push(o),t}),[]).sort(((t,e)=>t._index-e._index)).slice(0,1)[0]}const l=Math.PI,c=l/2;function d(t,n,i){return n=\"string\"==typeof n?t.parse(n):n instanceof Date?n.getTime():n,e.isFinite(n)?t.getPixelForValue(n):i}function h(t,e,n,i,o,a){if(t.beginPath(),a){const s=Math.min(a,o/2,i/2),r=e+s,d=n+s,h=e+i-s,u=n+o-s;t.moveTo(e,d),r<h&&d<u?(t.arc(r,d,s,-l,-c),t.arc(h,d,s,-c,0),t.arc(h,u,s,0,c),t.arc(r,u,s,c,l)):r<h?(t.moveTo(r,n),t.arc(h,d,s,-c,c),t.arc(r,d,s,c,l+c)):d<u?(t.arc(r,d,s,-l,0),t.arc(r,u,s,0,l)):t.arc(r,d,s,-l,l),t.closePath(),t.moveTo(e,n)}else t.rect(e,n,i,o)}class u extends t.Element{inRang",
		"e(t,e,n){const{x:i,y:o,width:a,height:s}=this.getProps([\"x\",\"y\",\"width\",\"height\"],n);return t>=i&&t<=i+a&&e>=o&&e<=o+s}getCenterPoint(t){const{x:e,y:n,width:i,height:o}=this.getProps([\"x\",\"y\",\"width\",\"height\"],t);return{x:e+i/2,y:n+o/2}}draw(t){const{x:e,y:n,width:i,height:o,options:a}=this;t.save(),t.lineWidth=a.borderWidth,t.strokeStyle=a.borderColor,t.fillStyle=a.backgroundColor,h(t,e,n,i,o,a.cornerRadius),t.fill(),t.stroke(),t.restore()}resolveElementProperties(t,e){const n=t.scales[e.xScaleID],i=t.scales[e.yScaleID];let o,a,{top:s,left:r,bottom:l,right:c}=t.chartArea;return n||i?(n&&(o=d(n,e.xMin,r),a=d(n,e.xMax,c),r=Math.min(o,a),c=Math.max(o,a)),i&&(o=d(i,e.yMin,l),a=d(i,e.yMax,s),s=Math.min(o,a),l=Math.max(o,a)),{x:r,y:s,x2:c,y2:l,width:c-r,height:l-s}):{options:{}}}}u.id=\"boxAnnotation\",u.defaults={display:!0,borderWidth:1,cornerRadius:0},u.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const f=Math.PI,y=(t,e,n)=>({x:t.x+n*(e.x-t.x),y:t.y+n*(e",
		".y-t.y)});class x extends t.Element{intersects(t,e,n){n=n||.001;const i=this,o={x:i.x,y:i.y},a={x:i.x2,y:i.y2},s=((t,e,n)=>y(e,n,Math.abs((t-e.x)/(n.x-e.x))).y)(t,o,a),r=((t,e,n)=>y(e,n,Math.abs((t-e.y)/(n.y-e.y))).x)(e,o,a);return(!isFinite(s)||Math.abs(e-s)<n)&&(!isFinite(r)||Math.abs(t-r)<n)}labelIsVisible(){const t=this.options.label;return t&&t.enabled&&t.content}isOnLabel(t,e){const{labelRect:n}=this;if(!n)return!1;const{x:i,y:o}=(a={x:t,y:e},s=n,r=-n.rotation,l=Math.cos(r),c=Math.sin(r),d=s.x,h=s.y,{x:d+l*(a.x-d)-c*(a.y-h),y:h+c*(a.x-d)+l*(a.y-h)});var a,s,r,l,c,d,h;const u=n.width/2,f=n.height/2;return i>=n.x-u&&i<=n.x+u&&o>=n.y-f&&o<=n.y+f}inRange(t,e){const n=this.options.borderWidth||1;return this.intersects(t,e,n)||this.isOnLabel(t,e)}getCenterPoint(){return{x:(this.x2+this.x)/2,y:(this.y2+this.y)/2}}draw(t){const{x:e,y:n,x2:i,y2:o,options:a}=this;t.save(),t.lineWidth=a.borderWidth,t.strokeStyle=a.borderColor,t.setLineDash&&t.setLineDash(a.borderDash),t.lineDashOffset=a.bord",
		"erDashOffset,t.beginPath(),t.moveTo(e,n),t.lineTo(i,o),t.stroke(),t.restore()}drawLabel(t,n){this.labelIsVisible()&&(t.save(),function(t,n,i){const o=n.options.label;t.font=e.toFontString(o.font),t.textAlign=\"center\";const{width:a,height:s}=function(t,n){const i=n.content,o=e.isArray(i)?i:[i],a=o.length;let s=0;for(let e=0;e<a;e++){const n=o[e];m.has(n)||m.set(n,t.measureText(n).width),s=Math.max(s,m.get(n))}return s+=2*n.xPadding,{width:s,height:a*n.font.size+(a+1)*n.yPadding}}(t,o),r=n.labelRect=function(t,n,i,o){const a=t.options.label,{xAdjust:s,yAdjust:r,xPadding:l,yPadding:c,position:d}=a,h={x:t.x,y:t.y},u={x:t.x2,y:t.y2},x=\"auto\"===a.rotation?function(t){const{x:e,y:n,x2:i,y2:o}=t,a=Math.atan2(o-n,i-e);return a>f/2?a-f:a<f/-2?a+f:a}(t):e.toRadians(a.rotation),m=function(t,e,n){const i=Math.cos(n),o=Math.sin(n);return{w:Math.abs(t*i)+Math.abs(e*o),h:Math.abs(t*o)+Math.abs(e*i)}}(n,i,x),g=function(t,e,n,i){let o=.5;const a=function(t,e){const{x:n,x2:i,y:o,y2:a}=t,s=Math.min(o,a",
		")-e.top,r=Math.min(n,i)-e.left,l=e.bottom-Math.max(o,a),c=e.right-Math.max(n,i);return{x:Math.min(r,c),y:Math.min(s,l),dx:r<c?1:-1,dy:s<l?1:-1}}(t,i),s=t.options.label;\"start\"===e?o=p({w:t.x2-t.x,h:t.y2-t.y},n,s,a):\"end\"===e&&(o=1-p({w:t.x-t.x2,h:t.y-t.y2},n,s,a));return o}(t,d,m,o),w=y(h,u,g),M={size:m.w,min:o.left,max:o.right,padding:l},v={size:m.h,min:o.top,max:o.bottom,padding:c};return{x:b(w.x,M)+s,y:b(w.y,v)+r,width:n,height:i,rotation:x}}(n,a,s,i);if(t.translate(r.x,r.y),t.rotate(r.rotation),t.fillStyle=o.backgroundColor,h(t,-a/2,-s/2,a,s,o.cornerRadius),t.fill(),t.fillStyle=o.color,e.isArray(o.content)){let e=-s/2+o.yPadding;for(let n=0;n<o.content.length;n++)t.textBaseline=\"top\",t.fillText(o.content[n],-a/2+a/2,e),e+=o.font.size+o.yPadding}else t.textBaseline=\"middle\",t.fillText(o.content,0,0)}(t,this,n),t.restore())}resolveElementProperties(t,e){const n=t.scales[e.scaleID];let i,o,{top:a,left:s,bottom:r,right:l}=t.chartArea;if(n)i=d(n,e.value,NaN),o=d(n,e.endValue,i),n",
		".isHorizontal()?(s=i,l=o):(a=i,r=o);else{const n=t.scales[e.xScaleID],i=t.scales[e.yScaleID];n&&(s=d(n,e.xMin,s),l=d(n,e.xMax,l)),i&&(a=d(i,e.yMin,a),r=d(i,e.yMax,r))}return{x:s,y:a,x2:l,y2:r,width:l-s,height:r-a}}}x.id=\"lineAnnotation\",x.defaults={display:!0,borderDash:[],borderDashOffset:0,label:{backgroundColor:\"rgba(0,0,0,0.8)\",font:{family:t.defaults.font.family,size:t.defaults.font.size,style:\"bold\"},color:\"#fff\",xPadding:6,yPadding:6,rotation:0,cornerRadius:6,position:\"center\",xAdjust:0,yAdjust:0,enabled:!1,content:null}};const m=new Map;function p(t,e,n,i){const{xPadding:o,yPadding:a}=n,s=t.w*i.dx,r=t.h*i.dy,l=s>0&&(e.w/2+o-i.x)/s,c=r>0&&(e.h/2+a-i.y)/r;return Math.max(Math.min(Math.max(l,c),.25),0)}function b(t,e){const{size:n,min:i,max:o,padding:a}=e,s=n/2;return n>o-i?(o+i)/2:(i>=t-a-s&&(t=i+a+s),o<=t+a+s&&(t=o-a-s),t)}class g extends u{inRange(t,e){return function(t,e){const{width:n,height:i}=e,o=e.getCenterPoint(!0),a=n/2,s=i/2;if(a<=0||s<=0)return!1;return Math.p",
		"ow(t.x-o.x,2)/Math.pow(a,2)+Math.pow(t.y-o.y,2)/Math.pow(s,2)<=1}({x:t,y:e},this)}draw(t){const{width:e,height:n,options:i}=this,o=this.getCenterPoint(!0);t.save(),t.beginPath(),t.lineWidth=i.borderWidth,t.strokeStyle=i.borderColor,t.fillStyle=i.backgroundColor,t.ellipse(o.x,o.y,n/2,e/2,Math.PI/2,0,2*Math.PI),t.fill(),t.stroke(),t.restore()}}g.id=\"ellipseAnnotation\",g.defaults={display:!0,borderWidth:1},g.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};class w extends t.Element{inRange(t,e){const{width:n,options:i}=this,o=this.getCenterPoint(!0),a=n/2+i.borderWidth;return!(a<=0)&&Math.pow(t-o.x,2)+Math.pow(e-o.y,2)<=Math.pow(a,2)}getCenterPoint(t){const{x:e,y:n}=this.getProps([\"x\",\"y\"],t);return{x:e,y:n}}draw(t){const{x:e,y:n,width:i,options:o}=this;t.save(),t.lineWidth=o.borderWidth,t.strokeStyle=o.borderColor,t.fillStyle=o.backgroundColor,t.beginPath(),t.arc(e,n,i/2,0,2*Math.PI),t.fill(),t.stroke(),t.restore()}resolveElementProperties(t,e){const{chartArea:n,scale",
		"s:i}=t,o=i[e.xScaleID],a=i[e.yScaleID];let s=n.width/2,r=n.height/2;return o&&(s=d(o,e.xValue,s)),a&&(r=d(a,e.yValue,r)),{x:s,y:r,width:2*e.radius,height:2*e.radius}}}w.id=\"pointAnnotation\",w.defaults={display:!0,borderWidth:1,radius:10,xScaleID:\"x\",yScaleID:\"y\"},w.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const M=new Map,v={box:u,line:x,ellipse:g,point:w};var P={id:\"annotation\",afterRegister(){t.Chart.register(v)},afterUnregister(){t.Chart.unregister(v)},beforeInit(t){M.set(t,{elements:[],listeners:{},listened:!1,moveListened:!1,scales:new Set})},afterDataLimits(t,n,i){const o=M.get(t);!function(t,n,i){const o=function(t,e){if(t&&t.length)return t.filter((t=>t._display)).map((t=>t.options));return e.annotations||[]}(n.elements,i),a=function(t,n){const i=t.axis,o=t.id,a=t.axis+\"ScaleID\",s=n.filter((t=>t[a]===o||t.scaleID===o));let r=e.valueOrDefault(t.min,Number.NEGATIVE_INFINITY),l=e.valueOrDefault(t.max,Number.POSITIVE_INFINITY);return s.forEach((t=>{[\"",
		"value\",\"endValue\",i+\"Min\",i+\"Max\",\"xValue\",\"yValue\"].forEach((e=>{if(e in t){const n=t[e];r=Math.min(r,n),l=Math.max(l,n)}}))})),{min:r,max:l}}(t,o);let s=!1;e.isFinite(a.min)&&void 0===t.options.min&&void 0===t.options.suggestedMin&&(s=t.min!==a.min,t.min=a.min);e.isFinite(a.max)&&void 0===t.options.max&&void 0===t.options.suggestedMax&&(s=t.max!==a.max,t.max=a.max);s&&\"function\"==typeof t.handleTickRangeOptions&&t.handleTickRangeOptions()}(n.scale,o,i)},beforeUpdate(t,n,i){if(e.isObject(i.annotations)){const t=new Array;Object.keys(i.annotations).forEach((n=>{const o=i.annotations[n];e.isObject(o)&&(o.id=n,t.push(o))})),i.annotations=t}},afterUpdate(a,s,r){const l=M.get(a);!function(t,e,a){const s=a.annotations||[];e.listened=!1,e.moveListened=!1,o.forEach((t=>{\"function\"==typeof a[t]&&(e.listened=!0,e.listeners[t]=a[t])})),i.forEach((t=>{\"function\"==typeof a[t]&&(e.moveListened=!0)})),e.listened&&e.moveListened||s.forEach((t=>{e.listened||n.forEach((n=>{\"function\"=",
		"=typeof t[n]&&(e.listened=!0)})),e.moveListened||i.forEach((n=>{\"function\"==typeof t[n]&&(e.listened=!0,e.moveListened=!0)}))}))}(0,l,r),function(n,i,o,a){const s=n.options.animation,r=s&&e.merge({},[s,o.animation]),l=function(e,n,i){if(\"reset\"===i||\"none\"===i||\"resize\"===i)return D;return new t.Animations(e,n)}(n,r,a),c=o.annotations||[],d=function(t,e){const n=e.length,i=t.length;if(i<n){const e=n-i;t.splice(i,0,...new Array(e))}else i>n&&t.splice(n,i-n);return t}(i.elements,c);for(let t=0;t<c.length;t++){const i=c[t];let o=d[t];const a=v[i.type]||v.line;o&&o instanceof a||(o=d[t]=new a);const s=o.resolveElementProperties(n,i);s.options=e.merge(Object.create(null),[a.defaults,i]),l.update(o,s);const r=\"function\"==typeof i.display?e.callback(i.display,[{chart:n,element:o}]):e.valueOrDefault(i.display,!0);o._display=!!r}}(a,l,r,s.mode)},beforeDatasetsDraw(t,e,n){k(t,n,\"beforeDatasetsDraw\")},afterDatasetsDraw(t,e,n){k(t,n,\"afterDatasetsDraw\")},beforeDraw(t,e,n){k(t,n,\"befo",
		"reDraw\")},afterDraw(t,e,n){k(t,n,\"afterDraw\")},beforeEvent(t,e,n){a(t,M.get(t),e.event,n)},destroy(t){M.delete(t)},_getState:t=>M.get(t),defaults:{drawTime:\"afterDatasetsDraw\",dblClickSpeed:350,annotations:{},animation:{numbers:{properties:[\"x\",\"y\",\"x2\",\"y2\",\"width\",\"height\"],type:\"number\"}}}};const D={update:Object.assign};function k(t,n,i){const{ctx:o,chartArea:a}=t,s=M.get(t).elements.filter((t=>t._display));e.clipArea(o,a),s.forEach((t=>{(t.options.drawTime||n.drawTime||i)===i&&t.draw(o)})),e.unclipArea(o),s.forEach((t=>{\"drawLabel\"in t&&t.options.label&&(t.options.label.drawTime||t.options.drawTime||n.drawTime||i)===i&&t.drawLabel(o,a)}))}return t.Chart.register(P),P}));",
		"//# sourceMappingURL=chartjs-plugin-annotation.min.js.map"
	};
	
	/**
	 * Creates the injectable resource with <code>chartjs-plugin-annotation.min.js</code> content.
	 */
	AnnotationPluginResource() {
		super(ResourceName.ANNOTATION_PLUGIN, CONTENT);
	}

}
