/**
    Copyright 2017 Andrea "Stock" Stocchero

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package org.pepstock.charba.client.annotation;

import org.pepstock.charba.client.resources.AbstractInjectableResource;
import org.pepstock.charba.client.resources.ResourceName;

/**
 * Contains the content of <code>chartjs-plugin-annotation.min.js</code> to inject.<br>
 * 
 * @author Andrea "Stock" Stocchero
 *
 */
public final class AnnotationPluginResource extends AbstractInjectableResource {

	// encoded javascript content of chartjs-plugin-annotation.min.js
	private static final String[] CONTENT = {
		"/*!",
		"* chartjs-plugin-annotation v1.0.0-beta.3",
		"* undefined",
		" * (c) 2021 chartjs-plugin-annotation Contributors",
		" * Released under the MIT License",
		" */",
		"!function(t,e){\"object\"==typeof exports&&\"undefined\"!=typeof module?module.exports=e(require(\"chart.js\"),require(\"chart.js/helpers\")):\"function\"==typeof define&&define.amd?define([\"chart.js\",\"chart.js/helpers\"],e):(t=\"undefined\"!=typeof globalThis?globalThis:t||self)[\"chartjs-plugin-annotation\"]=e(t.Chart,t.Chart.helpers)}(this,(function(t,e){\"use strict\";const n=[\"click\",\"dblclick\"],o=[\"enter\",\"leave\"],i=n.concat(o);function s(t,e,n){if(e.listened)switch(n.type){case\"mousemove\":case\"mouseout\":!function(t,e,n){if(!e.moveListened)return;let o;\"mousemove\"===n.type&&(o=r(e.elements,n));const i=e.hovered;e.hovered=o,function(t,e,n,o){n&&n!==o&&a(t,e,n.options.leave||e.listeners.leave,n);o&&o!==n&&a(t,e,o.options.enter||e.listeners.enter,o)}(t,e,i,o)}(t,e,n);break;case\"click\":!function(t,e,n){const o=e.options,i=e.listeners,s=r(e.elements,n);if(s){const n=s.options,r=n.dblclick||i.dblclick,l=n.click||i.click;s.clickTimeout?(clearTimeout(s.clickTimeout),del",
		"ete s.clickTimeout,a(t,e,r,s)):r?s.clickTimeout=setTimeout((()=>{delete s.clickTimeout,a(t,e,l,s)}),o.dblClickSpeed):a(t,e,l,s)}}(t,e,n)}}function a(t,n,o,i){e.callback(o,[{chart:t,element:i}])}function r(t,n){let o=Number.POSITIVE_INFINITY;return t.filter((t=>t.options.display&&t.inRange(n.x,n.y))).reduce(((t,i)=>{const s=i.getCenterPoint(),a=e.distanceBetweenPoints(n,s);return a<o?(t=[i],o=a):a===o&&t.push(i),t}),[]).sort(((t,e)=>t._index-e._index)).slice(0,1)[0]}const l=Math.PI,c=l/2;function d(t,n,o){return n=\"number\"==typeof n?n:t.parse(n),e.isFinite(n)?t.getPixelForValue(n):o}function h(t,e,n,o,i,s){if(t.beginPath(),s){const a=Math.min(s,i/2,o/2),r=e+a,d=n+a,h=e+o-a,u=n+i-a;t.moveTo(e,d),r<h&&d<u?(t.arc(r,d,a,-l,-c),t.arc(h,d,a,-c,0),t.arc(h,u,a,0,c),t.arc(r,u,a,c,l)):r<h?(t.moveTo(r,n),t.arc(h,d,a,-c,c),t.arc(r,d,a,c,l+c)):d<u?(t.arc(r,d,a,-l,0),t.arc(r,u,a,0,l)):t.arc(r,d,a,-l,l),t.closePath(),t.moveTo(e,n)}else t.rect(e,n,o,i)}class u extends t.Element{inRange(t,e,n){const{x:",
		"o,y:i,width:s,height:a}=this.getProps([\"x\",\"y\",\"width\",\"height\"],n);return t>=o&&t<=o+s&&e>=i&&e<=i+a}getCenterPoint(t){const{x:e,y:n,width:o,height:i}=this.getProps([\"x\",\"y\",\"width\",\"height\"],t);return{x:e+o/2,y:n+i/2}}draw(t){const{x:e,y:n,width:o,height:i,options:s}=this;t.save(),t.lineWidth=s.borderWidth,t.strokeStyle=s.borderColor,t.fillStyle=s.backgroundColor,h(t,e,n,o,i,s.cornerRadius),t.fill(),t.stroke(),t.restore()}resolveElementProperties(t,e){const n=t.scales[e.xScaleID],o=t.scales[e.yScaleID];let i,s,{top:a,left:r,bottom:l,right:c}=t.chartArea;return n||o?(n&&(i=d(n,e.xMin,r),s=d(n,e.xMax,c),r=Math.min(i,s),c=Math.max(i,s)),o&&(i=d(o,e.yMin,l),s=d(o,e.yMax,a),a=Math.min(i,s),l=Math.max(i,s)),{x:r,y:a,x2:c,y2:l,width:c-r,height:l-a}):{options:{}}}}u.id=\"boxAnnotation\",u.defaults={display:!0,xScaleID:\"x\",yScaleID:\"y\",borderWidth:1,cornerRadius:0},u.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const f=Math.PI,y=(t,e,n)=>({x:t.x+n*(e.x-t.",
		"x),y:t.y+n*(e.y-t.y)});class x extends t.Element{intersects(t,e,n){n=n||.001;const o=this,i={x:o.x,y:o.y},s={x:o.x2,y:o.y2},a=((t,e,n)=>y(e,n,Math.abs((t-e.x)/(n.x-e.x))).y)(t,i,s),r=((t,e,n)=>y(e,n,Math.abs((t-e.y)/(n.y-e.y))).x)(e,i,s);return(!isFinite(a)||Math.abs(e-a)<n)&&(!isFinite(r)||Math.abs(t-r)<n)}labelIsVisible(){const t=this.options.label;return t&&t.enabled&&t.content}isOnLabel(t,e){const{labelRect:n}=this;if(!n)return!1;const{x:o,y:i}=(s={x:t,y:e},a=n,r=-n.rotation,l=Math.cos(r),c=Math.sin(r),d=a.x,h=a.y,{x:d+l*(s.x-d)-c*(s.y-h),y:h+c*(s.x-d)+l*(s.y-h)});var s,a,r,l,c,d,h;const u=n.width/2,f=n.height/2;return o>=n.x-u&&o<=n.x+u&&i>=n.y-f&&i<=n.y+f}inRange(t,e){const n=this.options.borderWidth||1;return this.intersects(t,e,n)||this.isOnLabel(t,e)}getCenterPoint(){return{x:(this.x2+this.x)/2,y:(this.y2+this.y)/2}}draw(t){const{x:e,y:n,x2:o,y2:i,options:s}=this;t.save(),t.lineWidth=s.borderWidth,t.strokeStyle=s.borderColor,t.setLineDash&&t.setLineDash(s.borderDash),t.lineDash",
		"Offset=s.borderDashOffset,t.beginPath(),t.moveTo(e,n),t.lineTo(o,i),t.stroke(),t.restore()}drawLabel(t,n){this.labelIsVisible()&&(t.save(),function(t,n,o){const i=n.options.label;t.font=e.toFontString(i.font),t.textAlign=\"center\";const{width:s,height:a}=function(t,n){const o=n.content,i=e.isArray(o)?o:[o],s=i.length;let a=0;for(let e=0;e<s;e++){const n=i[e];p.has(n)||p.set(n,t.measureText(n).width),a=Math.max(a,p.get(n))}return a+=2*n.xPadding,{width:a,height:s*n.font.size+(s+1)*n.yPadding}}(t,i),r=n.labelRect=function(t,n,o,i){const s=t.options.label,{xAdjust:a,yAdjust:r,xPadding:l,yPadding:c,position:d}=s,h={x:t.x,y:t.y},u={x:t.x2,y:t.y2},x=\"auto\"===s.rotation?function(t){const{x:e,y:n,x2:o,y2:i}=t,s=Math.atan2(i-n,o-e);return s>f/2?s-f:s<f/-2?s+f:s}(t):e.toRadians(s.rotation),p=function(t,e,n){const o=Math.cos(n),i=Math.sin(n);return{w:Math.abs(t*o)+Math.abs(e*i),h:Math.abs(t*i)+Math.abs(e*o)}}(n,o,x),g=function(t,e,n,o){let i=.5;const s=function(t,e){const{x:n,x2:o,y:i,y2:s}=t,a",
		"=Math.min(i,s)-e.top,r=Math.min(n,o)-e.left,l=e.bottom-Math.max(i,s),c=e.right-Math.max(n,o);return{x:Math.min(r,c),y:Math.min(a,l),dx:r<c?1:-1,dy:a<l?1:-1}}(t,o),a=t.options.label;\"start\"===e?i=m({w:t.x2-t.x,h:t.y2-t.y},n,a,s):\"end\"===e&&(i=1-m({w:t.x-t.x2,h:t.y-t.y2},n,a,s));return i}(t,d,p,i),w=y(h,u,g),M={size:p.w,min:i.left,max:i.right,padding:l},v={size:p.h,min:i.top,max:i.bottom,padding:c};return{x:b(w.x,M)+a,y:b(w.y,v)+r,width:n,height:o,rotation:x}}(n,s,a,o);if(t.translate(r.x,r.y),t.rotate(r.rotation),t.fillStyle=i.backgroundColor,h(t,-s/2,-a/2,s,a,i.cornerRadius),t.fill(),t.fillStyle=i.color,e.isArray(i.content)){let e=-a/2+i.yPadding;for(let n=0;n<i.content.length;n++)t.textBaseline=\"top\",t.fillText(i.content[n],-s/2+s/2,e),e+=i.font.size+i.yPadding}else t.textBaseline=\"middle\",t.fillText(i.content,0,0)}(t,this,n),t.restore())}resolveElementProperties(t,e){const n=t.scales[e.scaleID];let o,i,{top:s,left:a,bottom:r,right:l}=t.chartArea;if(n)o=d(n,e.value,NaN),i=d(n,e.",
		"endValue,o),n.isHorizontal()?(a=o,l=i):(s=o,r=i);else{const n=t.scales[e.xScaleID],o=t.scales[e.yScaleID];n&&(a=d(n,e.xMin,a),l=d(n,e.xMax,l)),o&&(s=d(o,e.yMin,s),r=d(o,e.yMax,r))}return{x:a,y:s,x2:l,y2:r,width:l-a,height:r-s}}}x.id=\"lineAnnotation\",x.defaults={display:!0,borderWidth:2,borderDash:[],borderDashOffset:0,label:{backgroundColor:\"rgba(0,0,0,0.8)\",font:{family:t.defaults.font.family,size:t.defaults.font.size,style:\"bold\"},color:\"#fff\",xPadding:6,yPadding:6,rotation:0,cornerRadius:6,position:\"center\",xAdjust:0,yAdjust:0,enabled:!1,content:null}},x.defaultRoutes={borderColor:\"color\"};const p=new Map;function m(t,e,n,o){const{xPadding:i,yPadding:s}=n,a=t.w*o.dx,r=t.h*o.dy,l=a>0&&(e.w/2+i-o.x)/a,c=r>0&&(e.h/2+s-o.y)/r;return Math.max(Math.min(Math.max(l,c),.25),0)}function b(t,e){const{size:n,min:o,max:i,padding:s}=e,a=n/2;return n>i-o?(i+o)/2:(o>=t-s-a&&(t=o+s+a),i<=t+s+a&&(t=i-s-a),t)}class g extends u{inRange(t,e){return function(t,e){const{width:n,height:o}=e,i=e.",
		"getCenterPoint(!0),s=n/2,a=o/2;if(s<=0||a<=0)return!1;return Math.pow(t.x-i.x,2)/Math.pow(s,2)+Math.pow(t.y-i.y,2)/Math.pow(a,2)<=1}({x:t,y:e},this)}draw(t){const{width:e,height:n,options:o}=this,i=this.getCenterPoint(!0);t.save(),t.beginPath(),t.lineWidth=o.borderWidth,t.strokeStyle=o.borderColor,t.fillStyle=o.backgroundColor,t.ellipse(i.x,i.y,n/2,e/2,Math.PI/2,0,2*Math.PI),t.fill(),t.stroke(),t.restore()}}g.id=\"ellipseAnnotation\",g.defaults={display:!0,xScaleID:\"x\",yScaleID:\"y\",borderWidth:1},g.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};class w extends t.Element{inRange(t,e){const{width:n,options:o}=this,i=this.getCenterPoint(!0),s=n/2+o.borderWidth;return!(s<=0)&&Math.pow(t-i.x,2)+Math.pow(e-i.y,2)<=Math.pow(s,2)}getCenterPoint(t){const{x:e,y:n}=this.getProps([\"x\",\"y\"],t);return{x:e,y:n}}draw(t){const{x:e,y:n,width:o,options:i}=this;t.save(),t.lineWidth=i.borderWidth,t.strokeStyle=i.borderColor,t.fillStyle=i.backgroundColor,t.beginPath(),t.arc(e,n,o/2,0",
		",2*Math.PI),t.fill(),t.stroke(),t.restore()}resolveElementProperties(t,e){const{chartArea:n,scales:o}=t,i=o[e.xScaleID],s=o[e.yScaleID];let a=n.width/2,r=n.height/2;return i&&(a=d(i,e.xValue,a)),s&&(r=d(s,e.yValue,r)),{x:a,y:r,width:2*e.radius,height:2*e.radius}}}w.id=\"pointAnnotation\",w.defaults={display:!0,borderWidth:1,radius:10,xScaleID:\"x\",yScaleID:\"y\"},w.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const M=new Map,v={box:u,line:x,ellipse:g,point:w};var D={id:\"annotation\",afterRegister(){t.Chart.register(v)},afterUnregister(){t.Chart.unregister(v)},beforeInit(t){M.set(t,{elements:[],options:{},listeners:{},listened:!1,moveListened:!1,scales:new Set})},beforeUpdate(t,n,o){const i=M.get(t);i.options=e.clone(o);const s=i.options.annotations;if(e.isObject(s)){const n=new Array;Object.keys(s).forEach((o=>{let i=s[o];e.isObject(i)&&(i.id=o,n.push(I(t,i)))})),i.options.annotations=n}else if(e.isArray(s))for(var a=0;a<s.length;a++)s[a]=I(t,s[a]);else i.options.an",
		"notations=[]},afterDataLimits(t,n){if(\"category\"!==n.scale.type){const o=M.get(t);!function(t,n){const o=n.annotations.filter((t=>t.display)),i=function(t,n){const o=t.axis,i=t.id,s=t.axis+\"ScaleID\",a=n.filter((t=>t[s]===i||t.scaleID===i));let r=e.valueOrDefault(t.min,Number.NEGATIVE_INFINITY),l=e.valueOrDefault(t.max,Number.POSITIVE_INFINITY);return a.forEach((e=>{[\"value\",\"endValue\",o+\"Min\",o+\"Max\",o+\"Value\"].forEach((n=>{if(n in e){const o=t.parse(e[n]);r=Math.min(r,o),l=Math.max(l,o)}}))})),{min:r,max:l}}(t,o);let s=!1;e.isFinite(i.min)&&void 0===t.options.min&&void 0===t.options.suggestedMin&&(s=t.min!==i.min,t.min=i.min);e.isFinite(i.max)&&void 0===t.options.max&&void 0===t.options.suggestedMax&&(s=t.max!==i.max,t.max=i.max);s&&\"function\"==typeof t.handleTickRangeOptions&&t.handleTickRangeOptions()}(n.scale,o.options)}},afterUpdate(s,a){const r=M.get(s);!function(t,e){const s=e.options,a=s.annotations||[];e.listened=!1,e.moveListened=!1,i.forEach((t=>{\"function\"=",
		"=typeof s[t]&&(e.listened=!0,e.listeners[t]=s[t])})),o.forEach((t=>{\"function\"==typeof s[t]&&(e.moveListened=!0)})),e.listened&&e.moveListened||a.forEach((t=>{e.listened||n.forEach((n=>{\"function\"==typeof t[n]&&(e.listened=!0)})),e.moveListened||o.forEach((n=>{\"function\"==typeof t[n]&&(e.listened=!0,e.moveListened=!0)}))}))}(0,r),function(n,o,i){const s=o.options,a=n.options.animation,r=a&&e.merge({},[a,s.animation]),l=function(e,n,o){if(\"reset\"===o||\"none\"===o||\"resize\"===o)return P;return new t.Animations(e,n)}(n,r,i),c=s.annotations||[],d=function(t,e){const n=e.length,o=t.length;if(o<n){const e=n-o;t.splice(o,0,...new Array(e))}else o>n&&t.splice(n,o-n);return t}(o.elements,c);for(let t=0;t<c.length;t++){const e=c[t];let o=d[t];const i=v[e.type]||v.line;o&&o instanceof i||(o=d[t]=new i);const s=o.resolveElementProperties(n,e);s.options=e,l.update(o,s)}}(s,r,a.mode)},beforeDatasetsDraw(t){k(t,\"beforeDatasetsDraw\")},afterDatasetsDraw(t){k(t,\"afterDatasetsDraw\")},before",
		"Draw(t){k(t,\"beforeDraw\")},afterDraw(t){k(t,\"afterDraw\")},beforeEvent(t,e){s(t,M.get(t),e.event)},destroy(t){M.delete(t)},_getState:t=>M.get(t),defaults:{drawTime:\"afterDatasetsDraw\",dblClickSpeed:350,annotations:{},animation:{numbers:{properties:[\"x\",\"y\",\"x2\",\"y2\",\"width\",\"height\"],type:\"number\"}}}};const P={update:Object.assign};function I(t,n){const o=v[n.type]||v.line,i=e.merge(Object.create(null),[t.options.elements[o.id],n]);return i.display=!!e.resolve([i.display,!0],{chart:t,options:i}),i}function k(t,n){const{ctx:o,chartArea:i}=t,s=M.get(t),a=s.options,r=s.elements.filter((t=>t.options.display));e.clipArea(o,i),r.forEach((t=>{(t.options.drawTime||a.drawTime||n)===n&&t.draw(o)})),e.unclipArea(o),r.forEach((t=>{\"drawLabel\"in t&&t.options.label&&(t.options.label.drawTime||t.options.drawTime||a.drawTime||n)===n&&t.drawLabel(o,i)}))}return t.Chart.register(D),D}));",
		"//# sourceMappingURL=chartjs-plugin-annotation.min.js.map"
	};
	
	/**
	 * Creates the injectable resource with <code>chartjs-plugin-annotation.min.js</code> content.
	 */
	AnnotationPluginResource() {
		super(ResourceName.ANNOTATION_PLUGIN, CONTENT);
	}

}
