/**
    Copyright 2017 Andrea "Stock" Stocchero

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package org.pepstock.charba.client.annotation;

import org.pepstock.charba.client.resources.AbstractInjectableResource;
import org.pepstock.charba.client.resources.ResourceName;

/**
 * Contains the content of <code>chartjs-plugin-annotation.min.js</code> to inject.<br>
 * 
 * @author Andrea "Stock" Stocchero
 *
 */
public final class AnnotationPluginResource extends AbstractInjectableResource {

	// encoded javascript content of chartjs-plugin-annotation.min.js
	private static final String[] CONTENT = {
		"/*!",
		"* chartjs-plugin-annotation v1.0.0-beta.3",
		"* undefined",
		" * (c) 2021 chartjs-plugin-annotation Contributors",
		" * Released under the MIT License",
		" */",
		"!function(e,t){\"object\"==typeof exports&&\"undefined\"!=typeof module?module.exports=t(require(\"chart.js\"),require(\"chart.js/helpers\")):\"function\"==typeof define&&define.amd?define([\"chart.js\",\"chart.js/helpers\"],t):(e=\"undefined\"!=typeof globalThis?globalThis:e||self)[\"chartjs-plugin-annotation\"]=t(e.Chart,e.Chart.helpers)}(this,(function(e,t){\"use strict\";const n=[\"click\",\"dblclick\"],o=[\"enter\",\"leave\"],i=n.concat(o);function a(e,t,n,o){if(t.listened)switch(n.type){case\"mousemove\":case\"mouseout\":!function(e,t,n){if(!t.moveListened)return;let o;\"mousemove\"===n.type&&(o=r(t.elements,n));const i=t.hovered;t.hovered=o,function(e,t,n,o){n&&n!==o&&s(e,t,n.options.leave||t.listeners.leave,n);o&&o!==n&&s(e,t,o.options.enter||t.listeners.enter,o)}(e,t,i,o)}(e,t,n);break;case\"click\":!function(e,t,n,o){const i=t.listeners,a=r(t.elements,n);if(a){const n=a.options,r=n.dblclick||i.dblclick,l=n.click||i.click;a.clickTimeout?(clearTimeout(a.clickTimeout),delete a.cl",
		"ickTimeout,s(e,t,r,a)):r?a.clickTimeout=setTimeout((()=>{delete a.clickTimeout,s(e,t,l,a)}),o.dblClickSpeed):s(e,t,l,a)}}(e,t,n,o)}}function s(e,n,o,i){t.callback(o,[{chart:e,element:i}])}function r(e,n){let o=Number.POSITIVE_INFINITY;return e.filter((e=>e._display&&e.inRange(n.x,n.y))).reduce(((e,i)=>{const a=i.getCenterPoint(),s=t.distanceBetweenPoints(n,a);return s<o?(e=[i],o=s):s===o&&e.push(i),e}),[]).sort(((e,t)=>e._index-t._index)).slice(0,1)[0]}const l=Math.PI,c=l/2;function d(e,n,o){return n=\"number\"==typeof n?n:e.parse(n),t.isFinite(n)?e.getPixelForValue(n):o}function h(e,t,n,o,i,a){if(e.beginPath(),a){const s=Math.min(a,i/2,o/2),r=t+s,d=n+s,h=t+o-s,u=n+i-s;e.moveTo(t,d),r<h&&d<u?(e.arc(r,d,s,-l,-c),e.arc(h,d,s,-c,0),e.arc(h,u,s,0,c),e.arc(r,u,s,c,l)):r<h?(e.moveTo(r,n),e.arc(h,d,s,-c,c),e.arc(r,d,s,c,l+c)):d<u?(e.arc(r,d,s,-l,0),e.arc(r,u,s,0,l)):e.arc(r,d,s,-l,l),e.closePath(),e.moveTo(t,n)}else e.rect(t,n,o,i)}class u extends e.Element{inRange(e,t,n){const{x:o,y:i,width:a",
		",height:s}=this.getProps([\"x\",\"y\",\"width\",\"height\"],n);return e>=o&&e<=o+a&&t>=i&&t<=i+s}getCenterPoint(e){const{x:t,y:n,width:o,height:i}=this.getProps([\"x\",\"y\",\"width\",\"height\"],e);return{x:t+o/2,y:n+i/2}}draw(e){const{x:t,y:n,width:o,height:i,options:a}=this;e.save(),e.lineWidth=a.borderWidth,e.strokeStyle=a.borderColor,e.fillStyle=a.backgroundColor,h(e,t,n,o,i,a.cornerRadius),e.fill(),e.stroke(),e.restore()}resolveElementProperties(e,t){const n=e.scales[t.xScaleID],o=e.scales[t.yScaleID];let i,a,{top:s,left:r,bottom:l,right:c}=e.chartArea;return n||o?(n&&(i=d(n,t.xMin,r),a=d(n,t.xMax,c),r=Math.min(i,a),c=Math.max(i,a)),o&&(i=d(o,t.yMin,l),a=d(o,t.yMax,s),s=Math.min(i,a),l=Math.max(i,a)),{x:r,y:s,x2:c,y2:l,width:c-r,height:l-s}):{options:{}}}}u.id=\"boxAnnotation\",u.defaults={display:!0,borderWidth:1,cornerRadius:0},u.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const f=Math.PI,y=(e,t,n)=>({x:e.x+n*(t.x-e.x),y:e.y+n*(t.y-e.y)});class x extends e.El",
		"ement{intersects(e,t,n){n=n||.001;const o=this,i={x:o.x,y:o.y},a={x:o.x2,y:o.y2},s=((e,t,n)=>y(t,n,Math.abs((e-t.x)/(n.x-t.x))).y)(e,i,a),r=((e,t,n)=>y(t,n,Math.abs((e-t.y)/(n.y-t.y))).x)(t,i,a);return(!isFinite(s)||Math.abs(t-s)<n)&&(!isFinite(r)||Math.abs(e-r)<n)}labelIsVisible(){const e=this.options.label;return e&&e.enabled&&e.content}isOnLabel(e,t){const{labelRect:n}=this;if(!n)return!1;const{x:o,y:i}=(a={x:e,y:t},s=n,r=-n.rotation,l=Math.cos(r),c=Math.sin(r),d=s.x,h=s.y,{x:d+l*(a.x-d)-c*(a.y-h),y:h+c*(a.x-d)+l*(a.y-h)});var a,s,r,l,c,d,h;const u=n.width/2,f=n.height/2;return o>=n.x-u&&o<=n.x+u&&i>=n.y-f&&i<=n.y+f}inRange(e,t){const n=this.options.borderWidth||1;return this.intersects(e,t,n)||this.isOnLabel(e,t)}getCenterPoint(){return{x:(this.x2+this.x)/2,y:(this.y2+this.y)/2}}draw(e){const{x:t,y:n,x2:o,y2:i,options:a}=this;e.save(),e.lineWidth=a.borderWidth,e.strokeStyle=a.borderColor,e.setLineDash&&e.setLineDash(a.borderDash),e.lineDashOffset=a.borderDashOffset,e.beginPath(),e.m",
		"oveTo(t,n),e.lineTo(o,i),e.stroke(),e.restore()}drawLabel(e,n){this.labelIsVisible()&&(e.save(),function(e,n,o){const i=n.options.label;e.font=t.toFontString(i.font),e.textAlign=\"center\";const{width:a,height:s}=function(e,n){const o=n.content,i=t.isArray(o)?o:[o],a=i.length;let s=0;for(let t=0;t<a;t++){const n=i[t];m.has(n)||m.set(n,e.measureText(n).width),s=Math.max(s,m.get(n))}return s+=2*n.xPadding,{width:s,height:a*n.font.size+(a+1)*n.yPadding}}(e,i),r=n.labelRect=function(e,n,o,i){const a=e.options.label,{xAdjust:s,yAdjust:r,xPadding:l,yPadding:c,position:d}=a,h={x:e.x,y:e.y},u={x:e.x2,y:e.y2},x=\"auto\"===a.rotation?function(e){const{x:t,y:n,x2:o,y2:i}=e,a=Math.atan2(i-n,o-t);return a>f/2?a-f:a<f/-2?a+f:a}(e):t.toRadians(a.rotation),m=function(e,t,n){const o=Math.cos(n),i=Math.sin(n);return{w:Math.abs(e*o)+Math.abs(t*i),h:Math.abs(e*i)+Math.abs(t*o)}}(n,o,x),b=function(e,t,n,o){let i=.5;const a=function(e,t){const{x:n,x2:o,y:i,y2:a}=e,s=Math.min(i,a)-t.top,r=Math.min(n,o)-t.left",
		",l=t.bottom-Math.max(i,a),c=t.right-Math.max(n,o);return{x:Math.min(r,c),y:Math.min(s,l),dx:r<c?1:-1,dy:s<l?1:-1}}(e,o),s=e.options.label;\"start\"===t?i=p({w:e.x2-e.x,h:e.y2-e.y},n,s,a):\"end\"===t&&(i=1-p({w:e.x-e.x2,h:e.y-e.y2},n,s,a));return i}(e,d,m,i),w=y(h,u,b),M={size:m.w,min:i.left,max:i.right,padding:l},v={size:m.h,min:i.top,max:i.bottom,padding:c};return{x:g(w.x,M)+s,y:g(w.y,v)+r,width:n,height:o,rotation:x}}(n,a,s,o);if(e.translate(r.x,r.y),e.rotate(r.rotation),e.fillStyle=i.backgroundColor,h(e,-a/2,-s/2,a,s,i.cornerRadius),e.fill(),e.fillStyle=i.color,t.isArray(i.content)){let t=-s/2+i.yPadding;for(let n=0;n<i.content.length;n++)e.textBaseline=\"top\",e.fillText(i.content[n],-a/2+a/2,t),t+=i.font.size+i.yPadding}else e.textBaseline=\"middle\",e.fillText(i.content,0,0)}(e,this,n),e.restore())}resolveElementProperties(e,t){const n=e.scales[t.scaleID];let o,i,{top:a,left:s,bottom:r,right:l}=e.chartArea;if(n)o=d(n,t.value,NaN),i=d(n,t.endValue,o),n.isHorizontal()?(s=o,l=i):(a=o",
		",r=i);else{const n=e.scales[t.xScaleID],o=e.scales[t.yScaleID];n&&(s=d(n,t.xMin,s),l=d(n,t.xMax,l)),o&&(a=d(o,t.yMin,a),r=d(o,t.yMax,r))}return{x:s,y:a,x2:l,y2:r,width:l-s,height:r-a}}}x.id=\"lineAnnotation\",x.defaults={display:!0,borderDash:[],borderDashOffset:0,label:{backgroundColor:\"rgba(0,0,0,0.8)\",font:{family:e.defaults.font.family,size:e.defaults.font.size,style:\"bold\"},color:\"#fff\",xPadding:6,yPadding:6,rotation:0,cornerRadius:6,position:\"center\",xAdjust:0,yAdjust:0,enabled:!1,content:null}};const m=new Map;function p(e,t,n,o){const{xPadding:i,yPadding:a}=n,s=e.w*o.dx,r=e.h*o.dy,l=s>0&&(t.w/2+i-o.x)/s,c=r>0&&(t.h/2+a-o.y)/r;return Math.max(Math.min(Math.max(l,c),.25),0)}function g(e,t){const{size:n,min:o,max:i,padding:a}=t,s=n/2;return n>i-o?(i+o)/2:(o>=e-a-s&&(e=o+a+s),i<=e+a+s&&(e=i-a-s),e)}class b extends u{inRange(e,t){return function(e,t){const{width:n,height:o}=t,i=t.getCenterPoint(!0),a=n/2,s=o/2;if(a<=0||s<=0)return!1;return Math.pow(e.x-i.x,2)/Math.pow(a,2)+Ma",
		"th.pow(e.y-i.y,2)/Math.pow(s,2)<=1}({x:e,y:t},this)}draw(e){const{width:t,height:n,options:o}=this,i=this.getCenterPoint(!0);e.save(),e.beginPath(),e.lineWidth=o.borderWidth,e.strokeStyle=o.borderColor,e.fillStyle=o.backgroundColor,e.ellipse(i.x,i.y,n/2,t/2,Math.PI/2,0,2*Math.PI),e.fill(),e.stroke(),e.restore()}}b.id=\"ellipseAnnotation\",b.defaults={display:!0,borderWidth:1},b.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};class w extends e.Element{inRange(e,t){const{width:n,options:o}=this,i=this.getCenterPoint(!0),a=n/2+o.borderWidth;return!(a<=0)&&Math.pow(e-i.x,2)+Math.pow(t-i.y,2)<=Math.pow(a,2)}getCenterPoint(e){const{x:t,y:n}=this.getProps([\"x\",\"y\"],e);return{x:t,y:n}}draw(e){const{x:t,y:n,width:o,options:i}=this;e.save(),console.log(\"BorderColor\",i.borderColor),e.lineWidth=i.borderWidth,e.strokeStyle=i.borderColor,e.fillStyle=i.backgroundColor,e.beginPath(),console.log(\"arc\",t,n,o/2),e.arc(t,n,o/2,0,2*Math.PI),e.fill(),e.stroke(),e.restore()}resolveElem",
		"entProperties(e,t){const{chartArea:n,scales:o}=e,i=o[t.xScaleID],a=o[t.yScaleID];console.log(\"----------------------------------\"),console.log(\"xScale\",i,t.xScaleID),console.log(\"yScale\",a,t.yScaleID);let s=n.width/2,r=n.height/2;return console.log(\"x\",s,t.xValue,\"y\",r,t.yValue),i&&(console.log(\"dentro xscale\"),s=d(i,t.xValue,s)),a&&(console.log(\"dentro yscale\"),r=d(a,t.yValue,r)),console.log(\"x\",s,t.xValue,\"y\",r,t.yValue),console.log(\"----------------------------------\"),{x:s,y:r,width:2*t.radius,height:2*t.radius}}}w.id=\"pointAnnotation\",w.defaults={display:!0,borderWidth:1,radius:10,xScaleID:\"x\",yScaleID:\"y\"},w.defaultRoutes={borderColor:\"color\",backgroundColor:\"color\"};const M=new Map,v={box:u,line:x,ellipse:b,point:w};var D={id:\"annotation\",afterRegister(){e.Chart.register(v)},afterUnregister(){e.Chart.unregister(v)},beforeInit(e){M.set(e,{elements:[],listeners:{},listened:!1,moveListened:!1,scales:new Set})},afterDataLimits(e,n,o){\"category\"!==n.s",
		"cale.type&&function(e,n,o){const i=function(e,t){if(t.annotations&&t.annotations.length)return t.annotations.filter((t=>k(e,t)));return[]}(e,o),a=function(e,n){const o=e.axis,i=e.id,a=e.axis+\"ScaleID\",s=n.filter((e=>e[a]===i||e.scaleID===i));let r=t.valueOrDefault(e.min,Number.NEGATIVE_INFINITY),l=t.valueOrDefault(e.max,Number.POSITIVE_INFINITY);return s.forEach((t=>{[\"value\",\"endValue\",o+\"Min\",o+\"Max\",\"xValue\",\"yValue\"].forEach((n=>{if(n in t){const o=e.parse(t[n]);r=Math.min(r,o),l=Math.max(l,o)}}))})),{min:r,max:l}}(n,i);let s=!1;t.isFinite(a.min)&&void 0===n.options.min&&void 0===n.options.suggestedMin&&(s=n.min!==a.min,n.min=a.min);t.isFinite(a.max)&&void 0===n.options.max&&void 0===n.options.suggestedMax&&(s=n.max!==a.max,n.max=a.max);s&&\"function\"==typeof n.handleTickRangeOptions&&n.handleTickRangeOptions()}(e,n.scale,o)},beforeUpdate(e,n,o){if(t.isObject(o.annotations)){const e=new Array;Object.keys(o.annotations).forEach((n=>{const i=o.annotations[n];t.isObject(",
		"i)&&(i.id=n,e.push(i))})),o.annotations=e}},afterUpdate(a,s,r){const l=M.get(a);!function(e,t,a){const s=a.annotations||[];t.listened=!1,t.moveListened=!1,i.forEach((e=>{\"function\"==typeof a[e]&&(t.listened=!0,t.listeners[e]=a[e])})),o.forEach((e=>{\"function\"==typeof a[e]&&(t.moveListened=!0)})),t.listened&&t.moveListened||s.forEach((e=>{t.listened||n.forEach((n=>{\"function\"==typeof e[n]&&(t.listened=!0)})),t.moveListened||o.forEach((n=>{\"function\"==typeof e[n]&&(t.listened=!0,t.moveListened=!0)}))}))}(0,l,r),function(n,o,i,a){const s=n.options.animation,r=s&&t.merge({},[s,i.animation]),l=function(t,n,o){if(\"reset\"===o||\"none\"===o||\"resize\"===o)return P;return new e.Animations(t,n)}(n,r,a),c=i.annotations||[],d=function(e,t){const n=t.length,o=e.length;if(o<n){const t=n-o;e.splice(o,0,...new Array(t))}else o>n&&e.splice(n,o-n);return e}(o.elements,c);for(let e=0;e<c.length;e++){const o=c[e];let i=d[e];const a=v[o.type]||v.line;i&&i instanceof a||(i=d[e]=new a);const s=i.re",
		"solveElementProperties(n,o);s.options=t.merge(Object.create(null),[a.defaults,o]),l.update(i,s),i._display=k(n,o,i)}}(a,l,r,s.mode)},beforeDatasetsDraw(e,t,n){I(e,n,\"beforeDatasetsDraw\")},afterDatasetsDraw(e,t,n){I(e,n,\"afterDatasetsDraw\")},beforeDraw(e,t,n){I(e,n,\"beforeDraw\")},afterDraw(e,t,n){I(e,n,\"afterDraw\")},beforeEvent(e,t,n){a(e,M.get(e),t.event,n)},destroy(e){M.delete(e)},_getState:e=>M.get(e),defaults:{drawTime:\"afterDatasetsDraw\",dblClickSpeed:350,annotations:{},animation:{numbers:{properties:[\"x\",\"y\",\"x2\",\"y2\",\"width\",\"height\"],type:\"number\"}}}};const P={update:Object.assign};function k(e,n,o){return!!(\"function\"==typeof n.display?t.callback(n.display,[{chart:e,element:o}]):t.valueOrDefault(n.display,!0))}function I(e,n,o){const{ctx:i,chartArea:a}=e,s=M.get(e).elements.filter((e=>e._display));t.clipArea(i,a),s.forEach((e=>{(e.options.drawTime||n.drawTime||o)===o&&e.draw(i)})),t.unclipArea(i),s.forEach((e=>{\"drawLabel\"in e&&e.options.label&&(e.opt",
		"ions.label.drawTime||e.options.drawTime||n.drawTime||o)===o&&e.drawLabel(i,a)}))}return e.Chart.register(D),D}));",
		"//# sourceMappingURL=chartjs-plugin-annotation.min.js.map"
	};
	
	/**
	 * Creates the injectable resource with <code>chartjs-plugin-annotation.min.js</code> content.
	 */
	AnnotationPluginResource() {
		super(ResourceName.ANNOTATION_PLUGIN, CONTENT);
	}

}
