# **************************************
# * Charba GitHub Actions build script *
# * Copyright © 2020 pepstock.org      *
# **************************************

# workflow name
name: Build

# runs only on push events on branch master
on:
   push:
      branches:
         - master

# workflow environment and steps
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         # checkout the repository content
         - name: Checkout
           uses: actions/checkout@v2
           with:
             # Disabling shallow clone
             fetch-depth: 0
         # setup a Java JDK
         - name: Setup JDK
           uses: actions/setup-java@v1
           with:
             java-version: '11'
         # setup a Java JDK
         - name: Setup Node.js
           uses: actions/setup-node@v2    
           with:
             node-version: '12'         
         # run the ant build
         - name: Build
           run: ant buildAll
         # print out the artifacts list
         - name: Print artifacts
           run: ls -R ./dist