# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Build and deploy Next
# 
# Runs only on push events on branch 'master'
# and then publishes to gh-pages
#
on:
  push:
    branches:
      - master
      
# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  buildNext:
    runs-on: ubuntu-latest
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # uses JDK 8 because otherwise frames are not supported anymore
      # 
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # 
      # Run the build of project by ANT
      # 
      - name: Build
        run: ant deployJavadoc
      # 
      # Deploy javadoc to GitHub Pages as next version
      # 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadoc
          destination_dir: ./next
          enable_jekyll: false
          keep_files: false
          full_commit_message: Deploy javadoc to GitHub Pages as next version