# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Build
# 
# Runs only on push events on branch 'master'
# 
on:
  push:
    branches:
      - master

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      # 
      # Run the build of project by ANT
      # 
      - name: Build
        run: ant buildAll
      # 
      # Print out the artifacts list
      # 
      - name: Print artifacts
        run: ls -R ./dist

  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Remove 'pom.xml' otherwise Sonar will fail forcing to use Maven   
      # 
      - name: Remove pom
        run: rm -f pom.xml    
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      # 
      # Setup Node.js (for Sonar)
      # 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'         
      # 
      # Run the Sonar scan
      # 
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
