# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Deploy
# 
# Runs only on new tag has been pushed
# and then publishes to gh-pages
# 
on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 
      # Gets the tag to use as version
      # 
      - name: Get version
        id: version
        run: |
          echo ::set-output name=CHARBA_VERSION::${GITHUB_REF#refs/tags/} 
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # uses JDK 8 because otherwise frames are not supported anymore
      # 
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # 
      # Run the build of project by ANT
      # 
      - name: Build
        run: ant deployJavadoc
      # 
      # Deploy javadoc to GitHub Pages
      # "destination_dir" must be change on every deploy
      # 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadoc
          destination_dir: ./${{ steps.version.outputs.CHARBA_VERSION }}
          enable_jekyll: false
          keep_files: false
          full_commit_message: Deploy ${{ steps.version.outputs.CHARBA_VERSION }} javadoc to GitHub Pages
      # 
      # Deploy javadoc to GitHub Pages as current version
      # 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadoc
          destination_dir: ./current
          enable_jekyll: false
          keep_files: false
          full_commit_message: Deploy javadoc to GitHub Pages as current version