# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Load existing javadoc
# 
# Runs only on push events on branch 'deploy'
# and then publishes to gh-pages
#
on:
   push:
      branches:
         - deploy
# 
# Workflow environment and steps
# 
jobs:
   deploy:
      runs-on: ubuntu-latest
      
      steps:
         # 
         # Checkout the repository content
         # 
         - name: Checkout
           uses: actions/checkout@v2
           with:
             # Disabling shallow clone 
             fetch-depth: 0
         # 
         # Run the build of project by ANT
         # 
         - name: Unload javadoc
           run: ant -buildfile loadJavadoc.xml
         # 
         # Deploy redirect page to GitHub Pages
         # 
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./javadoc
             destination_dir: ./1.3
             enable_jekyll: false
             keep_files: false
             full_commit_message: Load javadoc 1.3 to GitHub Pages
